# Generated by Django 5.1 on 2024-10-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_forum_alter_chatmessage_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forummessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
