# Generated by Django 5.1 on 2024-10-19 11:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0007_forummessage_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forummessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])]),
        ),
    ]
