# Generated by Django 5.1 on 2024-10-31 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0010_announcement_target_user_alter_ticket_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.ticketcategory', verbose_name='واحد مربوطه'),
        ),
    ]
