# Generated by Django 5.1 on 2024-08-28 20:38

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
    ]
