# Generated by Django 5.1 on 2024-09-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_alter_transaction_amount_alter_transaction_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='has_premium',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('regular', 'معمولی'), ('support', 'پشتیبان'), ('moderator', 'مدیر')], default='regular', max_length=10),
        ),
    ]
