# Generated by Django 5.1 on 2024-09-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_customuser_blocked_customuser_has_premium_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='has_premium',
            field=models.BooleanField(default=False),
        ),
    ]
